#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include <pqxx/pqxx>

#define SAIR				-1
#define INIT				4
#define LOGIN_BIBLIOTECARIO 0
#define LOGIN_USUARIO		1
#define MENU_USUARIO		2
#define MENU_BIBLIOTECARIO	3

#define PESQUISAR_LIVRO_NOME_BIBLIOTECARIO	  1
#define PESQUISAR_LIVRO_AUTOR_BIBLIOTECARIO	  2
#define PESQUISAR_LIVRO_ASSUNTO_BIBLIOTECARIO 3
#define PESQUISAR_RESERVAS_BIBLIOTECARIO	  4
#define EMPRESTAR_LIVRO_BIBLIOTECARIO		  5
#define CADASTRAR_LIVRO_BIBLIOTECARIO		  6
#define CADASTRAR_PRATELEIRA_BIBLIOTECARIO	  7
#define CADASTRAR_ESTANTE_BIBLIOTECARIO		  8
#define VER_PERFIL_BIBLIOTECARIO			  9
#define LOGOFF_BIBLIOTECARIO				  10

#define PESQUISAR_LIVRO_NOME_USUARIO	   1
#define PESQUISAR_LIVRO_AUTOR_USUARIO	   2
#define PESQUISAR_LIVRO_ASSUNTO_USUARIO	   3
#define PESQUISAR_RESERVAS_USUARIO		   4
#define CONFERIR_LISTA_EMPRESTIMOS_USUARIO 5
#define CONFERIR_VALOR_MULTA_USUARIO	   6
#define PAGAR_MULTA_USUARIO				   7
#define VER_PERFIL_USUARIO				   8
#define LOGOFF_USUARIO					   9

#endif